version: '3'
services:

  spring-api:
    container_name: spring-api
    image: lugar2020/spring-backend
    restart: always
    ports:
      - 9090:9090
    networks:
      - my-network
    environment:
      DB_HOST: ""
      DB_NAME: db_test
      DB_USERNAME: admin
      DB_PASSWORD: ""

  angular-ui:
    container_name: angular-ui
    image: lugar2020/angular-frontend
    restart: always
    ports:
     - 5050:80
    networks:
      - my-network
    depends_on:
     - spring-api
    environment:
      API_URL: "http://16.170.202.220:9090/api/tutorials"

networks:
  my-network:
    driver: bridge
 
